    # Tracker
    if ($host = tracker-test.shinova.in) {
        return 301 https://test.shinova.in/tracker$request_uri;
    }

    # Insurance
    if ($host = insurance-test.shinova.in) {
        return 301 https://test.shinova.in/insurance$request_uri;
    }

    # Diagnostics
    if ($host = diagnostics-test.shinova.in) {
        return 301 https://test.shinova.in/Diagnostics$request_uri;
    }

    # Milestone
    if ($host = milestone-test.shinova.in) {
        return 301 https://test.shinova.in/milestone$request_uri;
    }

    # Indicators
    if ($host = indicators-test.shinova.in) {
        return 301 https://test.shinova.in/indicators$request_uri;
    }

    # Global
    if ($host = global-test.shinova.in) {
        return 301 https://test.shinova.in/global$request_uri;
    }
