e   
    upstream default_upstream{
    ### server XXX.XXX.XXX.XXX; ### $GROUPNAME ### DEFUPPROTO ###
        server 192.168.4.90;   ### DEFUPPROTO for common ###
    sticky path=/; keepalive 100;
    }
    upstream backend_security_upstream {
        server 192.168.10.171:2102;  
    }
    upstream backend_milestone_upstream {
        server 192.168.10.171:2900;  
    }
    upstream backend_indicators_upstream {
        server 192.168.10.171:1205;  
    }
    ### BACKEND GLOBAL UPSTREAM ###
    upstream backend_franchise_upstream {
        server 192.168.10.171:8181;  
    }
    upstream backend_franchiseapp_upstream {
        server 192.168.10.171:8190;  
    }
    upstream backend_global_upstream {
        server 192.168.10.171:6553;  
    }
    upstream backend_insurance_upstream {
        server 192.168.10.171:1305;  
    }
    upstream backend_tracker_upstream {
        server 192.168.10.171:2700;  
    }
    upstream backend_interface_upstream {
        server 192.168.10.171:3005;  
    }
    upstream backend_diagnostics_upstream {
        server 192.168.10.171:1071;  
    }
    upstream backend_profile_upstream {
        server 192.168.10.171:1020;
	}
	upstream backend_storetrust_upstream {
        server 192.168.10.171:1808;
	}
    upstream backend_corporatehealthcheckup_upstream {
        server 192.168.10.171:1210;
    }
    upstream backend_hmsinterface_upstream {
        server 192.168.10.171:3030;
    }
    upstream backend_experienceform_upstream {
        server 192.168.10.171:9797;
    }
    upstream backend_er_upstream {
        server 192.168.10.171:4625;
    }

    upstream backend_hr_upstream {
        server 192.168.10.171:5678;
    }
    ### FRONTEND COMBINED UPSTREAM ###
    upstream frontend_combined_upstream {
        server 192.168.4.90;  
    }






















